# entities_to_sql.py

def classify_entity(name: str) -> str:
    """Classify the entity type based on keywords."""
    n = name.lower()

    if "assembleia da república" in n:
        return "PARLIAMENT"
    if "presidência da república" in n:
        return "PRESIDENCY"
    if "tribunal" in n:
        return "COURT"
    if "região autónoma" in n or "açores" in n or "madeira" in n:
        return "AUTONOMOUS_REGION"
    if "governo" in n or "junta" in n or "conselho de ministros" in n:
        # Ex- at the same time means historical government
        return "HISTORICAL" if n.startswith("ex-") else "GOVERNMENT"
    if "ministério" in n or "ministérios" in n:
        return "HISTORICAL" if n.startswith("ex-") else "MINISTRY"

    # fallback: if nothing matched
    return "HISTORICAL" if n.startswith("ex-") else "MINISTRY"


def generate_sql(entities):
    values = []
    for e in entities:
        e = e.strip()
        if not e:
            continue
        etype = classify_entity(e)
        # escape single quotes
        safe_e = e.replace("'", "''")
        values.append(f"('{safe_e}', '{etype}')")
    sql = "INSERT INTO entities (name, type)\nVALUES\n  " + ",\n  ".join(values) + ";"
    return sql


if __name__ == "__main__":
    # Option 1: put your list directly here
    entities = [
        "Ex-Ministério da Agricultura - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Agricultura e Pescas - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Agricultura, Comércio e Pescas - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Comunicação Social - 1.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Cooperação - 9.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Coordenação Interterritorial - 9.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Cultura - 1.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Cultura e Coordenação Científica - 1.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Economia - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Educação - 10.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Educação e Ciência - 10.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação e Obras Públicas - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - (Obras Públicas, Habitação e Urbanismo) - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - 8.ª Delegação da Direcção-Geral da Contabilidade Pública - Departamento da Habitação e Obras Públicas",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - Departamento da Habitação e Obras Públicas - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Habitação, Obras Públicas e Transportes - Departamento dos Transportes - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Indústria e Comércio - 9.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Indústria e Energia - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Indústria e Energia - 9.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Marinha - 6.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Marinha - 6.ª Repartição da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Marinha - Defesa Nacional - Departamento da Marinha - 6.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Qualidade de Vida - 5.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério da Reforma Administrativa - 1.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério das Finanças e do Plano - 2.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério das Finanças e do Plano - Secretaria de Estado do Orçamento - Direcção-Geral da Contabilidade Pública - Direcção dos Serviços Gerais do Orçamento",
        "Ex-Ministério do Comércio e Turismo - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Comércio Externo - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Comércio Interno - 11.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Comércio, Energia e Exportação - 9.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Equipamento Social - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Equipamento Social - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Equipamento Social - Departamento da Habitação e Obras Públicas - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Equipamento Social - Transportes e Comunicações - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Equipamento Social e do Ambiente - 8.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Exército - 5.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Exército - Defesa Nacional - Departamento do Exército - 5.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério do Mar - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Ex-Ministério dos Transportes e Comunicações - 12.ª Delegação da Direcção-Geral da Contabilidade Pública",
        "Finança, Administração Interna e Infraestruturas e Habitação",
        "Finanças",
        "Finanças e Adjunto e Economia",
        "Finanças e Administração Interna",
        "Finanças e Agricultura",
        "Finanças e Agricultura e Alimentação",
        "Finanças e Agricultura e Mar",
        "Finanças e Agricultura e Pescas",
        "Finanças e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças e Ambiente",
        "Finanças e Ambiente e Ação Climática",
        "Finanças e Ambiente e da Transição Energética",
        "Finanças e Ambiente e Energia",
        "Finanças e Ambiente e Transição Energética",
        "Finanças e Ciência, Tecnologia e Ensino Superior",
        "Finanças e Cultura",
        "Finanças e Defesa Nacional",
        "Finanças e Economia",
        "Finanças e Economia e Mar",
        "Finanças e Educação",
        "Finanças e Educação, Ciência e Inovação",
        "Finanças e Habitação",
        "Finanças e Infraestruturas e Habitação",
        "Finanças e Justiça",
        "Finanças e Juventude e Modernização",
        "Finanças e Mar",
        "Finanças e Modernização do Estado e da Administração Pública",
        "Finanças e Planeamento",
        "Finanças e Planeamento e das Infraestruturas",
        "Finanças e Planeamento e Infraestruturas",
        "Finanças e Saúde",
        "Finanças e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Adjunto e Economia e Cultura",
        "Finanças, Adjunto e Economia e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Adjunto e Economia, Infraestruturas e Habitação, Ambiente e Transição Energética e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças, Adjunto e Planeamento e das Infraestruturas",
        "Finanças, Adjunto, Agricultura, Florestas e Desenvolvimento Rural e Mar",
        "Finanças, Adjunto, Ciência, Tecnologia e Ensino Superior, Planeamento e das Infraestruturas e Ambiente",
        "Finanças, Administração Interna e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças, Administração Interna e Ambiente",
        "Finanças, Administração Interna e Infraestruturas e Habitação",
        "Finanças, Administração Interna e Modernização do Estado e da Administração Pública",
        "Finanças, Administração Interna e Planeamento e das Infraestruturas",
        "Finanças, Administração Interna, Ambiente e Transição Energética, Agricultura, Florestas e Desenvolvimento Rural e Mar",
        "Finanças, Administração Interna, Ciência, Tecnologia e Ensino Superior, Educação, Infraestruturas e Habitação e Ambiente e Transição Energética",
        "Finanças, Administração Interna, Ciência, Tecnologia e Ensino Superior, Educação, Planeamento e das Infraestruturas e Ambiente",
        "Finanças, Administração Interna, Planeamento e das Infraestruturas e Ambiente",
        "Finanças, Administração Interna, Planeamento e Infraestruturas e Ambiente e Transição Energética",
        "Finanças, Ambiente e Ação Climática e Agricultura e Alimentação",
        "Finanças, Ambiente e Ação Climática, Agricultura e Mar",
        "Finanças, Ambiente e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças, Ambiente e Energia e Juventude e Modernização",
        "Finanças, Ambiente e Transição Energética e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças, Ambiente, Agricultura, Florestas e Desenvolvimento Rural e Mar",
        "Finanças, Ciência, Tecnologia e Ensino Superior e Educação",
        "Finanças, Ciência, Tecnologia e Ensino Superior, Educação e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Defesa Nacional e Saúde",
        "Finanças, Defesa Nacional, Administração Interna, Justiça, Modernização do Estado e da Administração Pública e Saúde",
        "Finanças, Defesa Nacional, Administração Interna, Saúde e Mar",
        "Finanças, Defesa Nacional, Ambiente e Ação Climática e Infraestruturas e Habitação",
        "Finanças, Defesa Nacional, Justiça, Modernização do Estado e da Administração Pública e Saúde",
        "Finanças, Economia e Ambiente",
        "Finanças, Economia e Mar e Ciência, Tecnologia e Ensino Superior",
        "Finanças, Economia e Mar e Cultura",
        "Finanças, Economia e Mar e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Economia e Mar, Cultura, Trabalho, Solidariedade e Segurança Social, Infraestruturas e Coesão Territorial",
        "Finanças, Economia, Ambiente e Energia e Agricultura e Pescas",
        "Finanças, Economia, Trabalho, Solidariedade e Segurança Social e Agricultura e Pescas",
        "Finanças, Educação e Ambiente",
        "Finanças, Educação e Coesão Territorial",
        "Finanças, Educação e Saúde",
        "Finanças, Educação e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Educação, Ciência e Inovação e Economia",
        "Finanças, Infraestruturas e Habitação",
        "Finanças, Infraestruturas e Habitação e Ambiente e Energia",
        "Finanças, Infraestruturas e Habitação e Ambiente e Transição Energética",
        "Finanças, Infraestruturas e Habitação e Coesão Territorial",
        "Finanças, Infraestruturas e Habitação e Juventude e Modernização",
        "Finanças, Justiça e Educação, Ciência e Inovação",
        "Finanças, Justiça e Modernização do Estado e da Administração Pública",
        "Finanças, Justiça e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Justiça, Modernização do Estado e da Administração Pública, Ambiente e Ação Climática, Coesão Territorial e Agricultura",
        "Finanças, Modernização do Estado e da Administração Pública e Ambiente e Ação Climática",
        "Finanças, Modernização do Estado e da Administração Pública e Educação",
        "Finanças, Modernização do Estado e da Administração Pública e Saúde",
        "Finanças, Modernização do Estado e da Administração Pública e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Modernização do Estado e da Administração Pública, Cultura e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Planeamento e Ciência, Tecnologia e Ensino Superior",
        "Finanças, Planeamento e das Infraestruturas, Agricultura, Florestas e Desenvolvimento Rural e Mar",
        "Finanças, Planeamento e Infraestruturas e Ambiente e Transição Energética",
        "Finanças, Planeamento e Saúde",
        "Finanças, Saúde e Ambiente e Energia",
        "Finanças, Saúde e Economia",
        "Finanças, Saúde e Trabalho, Solidariedade e Segurança Social",
        "Finanças, Saúde, Ambiente e Ação Climática e Agricultura",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Agricultura e Alimentação",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Agricultura e Pescas",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Agricultura, Florestas e Desenvolvimento Rural",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Ambiente e Ação Climática",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Coesão Territorial",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Economia",
        "Finanças, Trabalho, Solidariedade e Segurança Social e Saúde",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério da Agricultura e Pescas",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério da Educação",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério da Educação e Cultura",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério da Habitação e Obras Públicas",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério das Finanças e do Plano",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério do Comércio e Turismo",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério do Planeamento e da Administração do Território",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério dos Assuntos Sociais",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministério dos Transportes e Comunicações",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios da Educação e da Saúde",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios da Justiça e da Habitação, Obras Públicas e Transportes",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios das Finanças e do Plano e da Indústria e Energia",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios das Finanças e do Plano e dos Assuntos Sociais",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios das Finanças e do Plano, do Comércio e Turismo e do Trabalho",
        "Gabinete do Ministro da República para a Região Autónoma da Madeira e Ministérios das Finanças e dos Assuntos Sociais",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministério da Educação",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministério da Indústria",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministério das Finanças e do Plano",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministério dos Assuntos Sociais",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministérios da Educação e da Saúde",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministérios das Finanças e do Plano e da Indústria e Energia",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministérios das Finanças, da Agricultura, Pescas e Alimentação e do Comércio e Turismo",
        "Gabinete do Ministro da República para a Região Autónoma dos Açores e Ministérios do Planeamento e da Administração do Território e da Educação",
        "Gabinete do Representante da República para a Região Autónoma da Madeira",
        "Gabinete do Representante da República para a Região Autónoma da Madeira",
        "Gabinete do Representante da República para a Região Autónoma dos Açores",
        "Gabinete do Representante da República para a Região Autónoma dos Açores",
        "Gabinetes dos Ministros da República das Regiões Autónomas da Madeira e dos Açores e Ministério das Finanças e do Plano",
        "Gabinetes dos Ministros da República para as Regiões Autónomas da Madeira e dos Açores e Ministério da Educação",
        "Gabinetes dos Ministros da República para as Regiões Autónomas da Madeira e dos Açores e Ministério das Finanças",
        "Gabinetes dos Ministros da República para as Regiões Autónomas da Madeira e dos Açores e Ministérios da Agricultura, Pescas e Alimentação e da Indústria e Comércio",
        "Gabinetes dos Ministros da República para as Regiões Autónomas dos Açores e da Madeira e Ministério da Agricultura, Pescas e Alimentação",
        "Gabinetes dos Ministros da República para as Regiões Autónomas dos Açores e da Madeira e Ministérios da Agricultura e do Comércio e Turismo",
        "Gabinetes dos Ministros da República para as Regiões Autónomas dos Açores e da Madeira e Ministérios da Agricultura, Pescas e Alimentação e do Comércio e Turismo",
        "Gabinetes dos Ministros da República para as Regiões Autónomas dos Açores e da Madeira e Ministérios das Finanças, da Economia e da Agricultura, do Desenvolvimento Rural e das Pescas",
        "Govêrno do distrito autónomo do Funchal",
        "Governo Provisorio da Republica",
        "Habitação",
        "Habitação e Coesão Territorial",
        "Infraestruturas",
        "Infraestruturas e Habitação",
        "Infraestruturas e Habitação e Agricultura",
        "Infraestruturas e Habitação e Ambiente e Energia",
        "Infraestruturas e Habitação e Ambiente e Transição Energética",
        "Infraestruturas e Habitação e Cultura",
        "Infraestruturas e Habitação e Juventude e Modernização",
        "Junta de Salvação Nacional",
        "Junta de Salvação Nacional - Estado-Maior-General das Forças Armadas",
        "Junta de Salvação Nacional - Gabinete do Presidente",
        "Junta Revolucionária",
        "Justiça",
        "Justica e Adjunto e Economia",
        "Justiça e Ambiente e Ação Climática",
        "Justiça e Cultura",
        "Justica e Educação",
        "Justiça e Educação",
        "Justiça e Finanças",
        "Justiça e Infraestruturas e Habitação",
        "Justiça e Juventude e Modernização",
        "Justiça e Modernização do Estado e da Administração Pública",
        "Justiça e Saúde",
        "Justiça e Trabalho, Solidariedade e Segurança Social",
        "Justiça, Administração Interna e Juventude e Modernização",
        "Justiça, Finanças e Coesão Territorial",
        "Justiça, Modernização do Estado e da Administração Pública e Infraestruturas e Habitação",

    ]

    # Option 2: read from file (uncomment if you have entities.txt with one per line)
    # with open("entities.txt", "r", encoding="utf-8") as f:
    #     entities = f.readlines()

    sql = generate_sql(entities)
    print(sql)
